folio-org/ui-organization

- constants.js
- settings/SSOSettings.js
Add new configuration options + metadata download option for SSO.
> UIORG-25 sso config

- package.json
@wafschneider we released the Login SAML module and updated the interface declaration so I changed the reference in the package.json. Could you check and merge my PR if it is okay?
> UIORG-37 Update login-saml interface name

- CHANGELOG.md
- package.json
Fixes UIORG-38 (at least, with the present git master)
> Upgrade stripes-connect dependency to v3.0.0-pre.1

- settings/SSOSettings.js
- settings/SamlForm.js
Please someone merge my commit if it seems good as I do not have write permission to the repository.
> UIORG-59 Hide Okapi URL setting from user

- package.json
- settings/BindingsForm.js
- settings/SSOSettings.js
- settings/SamlForm.js
- settings/ShelvingLocationsSettings.js
- settings/index.js
- translations/en.json
Use react-intl to translate previously hardcoded strings
> UIORG-46: i18n

- settings/Plugins.js
https://issues.folio.org/browse/UIORG-46
> UIORG-46: translate callout message

- CHANGELOG.md
- settings/LocationInstitutions.js
- settings/index.js
- translations/en.json
Fixes [UIORG-54](https://issues.folio.org/browse/UIORG-54)
> Location-Institution CRUD. Fixes UIORG-54

- .gitignore
- CHANGELOG.md
- settings/ServicePoints/ServicePointDetail.js
- settings/ServicePoints/ServicePointForm.js
- settings/ServicePoints/ServicePointManager.js
- settings/ServicePoints/index.js
- settings/index.js
- translations/en.json
https://issues.folio.org/browse/UIORG-50
> Add Service Point CRUD. Fixes UIORG-50.

- package.json
- settings/LocationCampuses.js
- settings/LocationInstitutions.js
- settings/LocationLibraries.js
- settings/index.js
Refs [UIORG-54](https://issues.folio.org/browse/UIORG-54), [UIORG-61](https://issues.folio.org/browse/UIORG-61), [UIORG-65](https://issues.folio.org/browse/UIORG-65)
> CRUD location institutions, campuses, libraries

- settings/LocationCampuses.js
- settings/LocationLibraries.js
- translations/en.json
Refs [UIORG-54](https://issues.folio.org/browse/UIORG-54), [UIORG-61](https://issues.folio.org/browse/UIORG-61), [UIORG-65](https://issues.folio.org/browse/UIORG-65)
> i18n strings. Refs UIORG-54, UIORG-61, UIORG-65

- settings/LocationLibraries.js
Refs [UIORG-65](https://issues.folio.org/browse/UIORG-65)
> translation key fixes. Refs UIORG-65

- settings/LocationCampuses.js
- settings/LocationLibraries.js
Surely this is wrong, and yet I'm not sure what the right approach would
be. This is a select list so we certainly don't want paging here; we want _all_ the values.
Refs [UIORG-61](https://issues.folio.org/browse/UIORG-61), [UIORG-65](https://issues.folio.org/browse/UIORG-65).
> increase default fetch limits.

- CHANGELOG.md
- settings/ShelvingLocationsSettings.js
Fixes [FOLIO-1208](https://issues.folio.org/browse/FOLIO-1208)
> fix up panel display for shelving locations. Fixes FOLIO-1208

- CHANGELOG.md
- settings/ServicePoints/ServicePointDetail.js
- settings/ServicePoints/ServicePointForm.js
https://issues.folio.org/browse/UIORG-74
> Remove fee fine owner. Fixes UIORG-74

- package.json
- settings/LocationLocations/LocationForm.js
- settings/ServicePoints/ServicePointForm.js
- translations/en.json
https://issues.folio.org/browse/UIORG-52
> Adjust delete message. Part of UIORG-52

- CHANGELOG.md
- settings/LocationLocations/DetailsField.js
- settings/LocationLocations/LocationDetail.js
- settings/LocationLocations/LocationForm.js
- settings/LocationLocations/LocationManager.js
- translations/en.json
Add remaining location fields: discovery display name, description, and details. 
> additional location fields. Refs UIORG-69

- package.json
- settings/index.js
- translations/en.json
Refs [UIORG-75](https://issues.folio.org/browse/UIORG-75)
> settings page sections. Refs UIORG-75

- CHANGELOG.md
- package.json
Fixes [UIORG-76](https://issues.folio.org/browse/UIORG-76)
> add location permission set. Fixes UIORG-76

- package.json
Part of https://issues.folio.org/browse/UIORG-50
> Add service point interface. Part of UIORG-50

- CHANGELOG.md
- settings/LocationLibraries.js
Refs [UIORG-66](https://issues.folio.org/browse/UIORG-66)
> include location-count on libraries page

- CHANGELOG.md
- settings/LocationCampuses.js
- settings/LocationInstitutions.js
- settings/LocationLibraries.js
Refs [UIORG-60](https://issues.folio.org/browse/UIORG-60), [UIORG-63](https://issues.folio.org/browse/UIORG-63), [UIORG-66](https://issues.folio.org/browse/UIORG-66)
> refresh location count on mount

- package.json
Refs [UIORG-76](https://issues.folio.org/browse/UIORG-76)
> renaming location permission set per request

- package.json
- settings/LocationCampuses.js
- settings/LocationInstitutions.js
- settings/LocationLibraries.js
- settings/LocationLocations/LocationDetail.js
- settings/LocationLocations/LocationManager.js
- settings/Plugins.js
- settings/SSOSettings.js
- settings/ServicePoints/ServicePointManager.js
Includes upgrade to `eslint-config-stripes` 2.0.
> Use stripes-config instead of deprecated stripes-loader

- settings/LocationCampuses.js
Missed a reference in my previous PR
> old context cleanup

- CHANGELOG.md
- settings/ServicePoints/EditableLocationList.js
- settings/ServicePoints/LocationList.js
- settings/ServicePoints/ServicePointDetail.js
- settings/ServicePoints/ServicePointForm.js
- settings/ServicePoints/ServicePointManager.js
https://issues.folio.org/browse/UIORG-90
> Assign locations to service points. Fixes UIORG-90.

- CHANGELOG.md
- settings/LocationLocations/LocationManager.js
Also, sort them by name.
Fixes UIORG-101.
> In the location manager in the settings, fetch up to 40 locations (was 10)

- CHANGELOG.md
- package.json
- settings/ServicePoints/EditableLocationList.js
https://issues.folio.org/browse/UIORG-104
> Clicking Save and close on location lookup popup should register the location. Fixes UIORG-104.

- translations/ui-organization/hu.json
> Update translation strings as of 20180924T185314

- CHANGELOG.md
- settings/Locale.js
Fixes [UIORG-113](https://issues.folio.org/browse/UIORG-113)
> expose Portuguese as a localization option

- CHANGELOG.md
- settings/LocationLocations/LocationForm.js
- settings/LocationLocations/LocationManager.js
https://issues.folio.org/browse/UIORG-117
> Add ability to copy location record. Fixes UIORG-117.

- CHANGELOG.md
- settings/LocationLocations/LocationManager.js
- translations/ui-organization/en.json
https://issues.folio.org/browse/UIORG-92
> Enable filtering of location records by institution, campus and library. Fixes UIORG-92.

- CHANGELOG.md
- settings/ServicePoints/ServicePointForm.js
- settings/ServicePoints/ServicePointManager.js
https://issues.folio.org/browse/UIORG-118
> Show correct Pickup Location flag. Fixes UIORG-118

- test/ui-testing/locations.js
This PR updates location creation based on the filtering work done in UIORG-92.
> Add tests to cover location filtering. Part of UIORG-92

- settings/LocationLocations/LocationDetail.js
- settings/LocationLocations/LocationForm.js
- settings/LocationLocations/LocationManager.js
- settings/LocationLocations/ServicePointsFields.js
- Adjust styling to the service points label
- Mark the last existing service point as primary
- Sort service points alphabetically
- Add id on the service point field
> Logic and styling updates to service point fields, refs UIORG-115

- settings/LocationLocations/LocationForm.js
- settings/LocationLocations/LocationManager.js
- settings/LocationLocations/ServicePointsFields.css
- settings/LocationLocations/ServicePointsFields.js
- Disable the add button once the service point list runs out of options
- Add styling to the field rows and legend
- Add validations on the fields
> Add styling and validation to service point fields, refs UIORG--115

- translations/ui-organization/ca.json
- translations/ui-organization/da.json
- translations/ui-organization/de.json
- translations/ui-organization/es.json
- translations/ui-organization/es_ES.json
- translations/ui-organization/fr.json
- translations/ui-organization/fr_FR.json
- translations/ui-organization/hu.json
- translations/ui-organization/it_IT.json
- translations/ui-organization/pt_BR.json
> Update translation strings as of 20181026T143111

- translations/ui-organization/ar.json
> Update translation strings as of 20181110T181812

- src/settings/LocationLocations/DetailsField.js
- src/settings/LocationLocations/LocationDetail.js
- src/settings/LocationLocations/LocationForm.js
- src/settings/LocationLocations/ServicePointsFields.js
Cleaning up a bunch of old stuff based on `stripes.intl` that got missed
in the initial sweep in #158.
Refs [UIORG-124](https://issues.folio.org/browse/UIORG-124)
> translation cleanup pursuant to #158

- test/ui-testing/locations.js
There's something wonky with location deletion, maybe related to
`<Callout>` but I'm not certain. These tweaks attempt to work around
that.
> even more reliable location tests

- CHANGELOG.md
- src/settings/ServicePoints/LocationList.js
- src/settings/ServicePoints/ServicePointDetail.js
- src/settings/ServicePoints/ServicePointForm.js
- src/settings/ServicePoints/ServicePointManager.js
https://issues.folio.org/browse/UIORG-127
> Display locations associated with the service point. Fixes UIORG-127

- src/settings/ServicePoints/ServicePointDetail.js
- src/settings/ServicePoints/ServicePointForm.js
https://issues.folio.org/browse/UIORG-127
> Show locations on service point details screen. Part of UIORG-127

- CHANGELOG.md
- src/settings/ServicePoints/DisallowDeleteModal.js
- src/settings/ServicePoints/ServicePointForm.js
- src/settings/ServicePoints/ServicePointManager.js
- translations/ui-organization/en.json
https://issues.folio.org/browse/UIORG-129
> Disallow deletion of SPs that are primary for location. Fixes UIORG-129

- src/settings/LocationLocations/LocationForm.js
- src/settings/LocationLocations/LocationManager.js
A couple instances of `stripes.intl` snuck past https://github.com/folio-org/ui-organization/pull/158.
> Replace stripes.intl

- translations/ui-organization/ar.json
- translations/ui-organization/ca.json
- translations/ui-organization/da.json
- translations/ui-organization/de.json
- translations/ui-organization/es.json
- translations/ui-organization/es_ES.json
- translations/ui-organization/fr.json
- translations/ui-organization/fr_FR.json
- translations/ui-organization/hu.json
- translations/ui-organization/it_IT.json
- translations/ui-organization/pt_BR.json
> Update translation strings as of 20181128T202334

- CHANGELOG.md
- src/settings/ServicePoints/ServicePointForm.js
https://issues.folio.org/browse/UIORG-130
> Hide service point delete button. Part of UIORG-130

- translations/ui-organization/pt_PT.json
> Update translation strings as of 20181212T135930

- src/settings/LocationLocations/LocationForm.js
- src/settings/ServicePoints/ServicePointForm.js
`times` replaced `closeX` some time ago.
> don't use deprecated icons

- src/settings/LocationLocations/LocationForm.js
`<IfPermission>` moved from components to core.
> import IfPermission from core

- src/settings/ServicePoints/ServicePointManager.js
- src/settings/ServicePoints/StaffSlipList.js
- test/bigtest/interactors/service-point-create.js
- test/bigtest/tests/service-point-create-test.js
This PR sets print slip defaults as checked by default. This is a missed requirement from UIORG-144
> Set print slip defaults as checked by default. Part of UIORG-144

- src/settings/ServicePoints/ServicePointDetail.js
- src/settings/ServicePoints/ServicePointForm.js
https://issues.folio.org/browse/UIORG-144
> Fix staff slip order. Refs UIORG-144

- src/settings/ServicePoints/ServicePointForm.js
The title attribute should not be use for accessibility.
Refs [STCOM-296](https://issues.folio.org/browse/STCOM-296)
> don't use the title attribute for html elements

- translations/ui-organization/zh_CN.json
> Update translation strings as of 20190219T224024

- translations/ui-organization/ar.json
- translations/ui-organization/ca.json
- translations/ui-organization/da.json
- translations/ui-organization/de.json
- translations/ui-organization/en_GB.json
- translations/ui-organization/en_SE.json
- translations/ui-organization/en_US.json
- translations/ui-organization/es.json
- translations/ui-organization/es_ES.json
- translations/ui-organization/fr.json
- translations/ui-organization/fr_FR.json
- translations/ui-organization/hu.json
- translations/ui-organization/it_IT.json
- translations/ui-organization/pt_BR.json
- translations/ui-organization/pt_PT.json
- translations/ui-organization/zh_CN.json
> Update translation strings as of 20190225T222207

- translations/ui-organization/ar.json
- translations/ui-organization/pt_BR.json
> Update translation strings as of 20190227T140407

- CHANGELOG.md
- src/settings/LocationLocations/LocationManager.js
Refs [UIORG-137](https://issues.folio.org/browse/UIORG-137)
> increase location fetch limit

- src/components/RepeatableField/FieldRow.js
Refs [STCOM-489](https://issues.folio.org/browse/STCOM-489)
> change trashBin to trash, fixing the typo

- src/settings/Locale.js
> Add Spanish and Spanish (Latin America)
