- settings/Locale.js
Hi there, I saw the same issue as described in UIORG-29 in our demo environment (error thrown when changing locale). Debugged and figured out that "metadata" property is not accepted anymore by backend mod-configuration due to schema change.
> Fix for UIORG-29

- package.json
- settings/Bindings.js
- settings/Locale.js
- settings/Plugins.js
- settings/SSOSettings.js
Old versions of react-bootstrap barf up the `Warning: Accessing PropTypes via the main React package is deprecated...` message. We could just upgrade, but are working to deprecate react-bootstrap anyway.
> don't use react-bootstrap's Row, Col. Refs STRIPES-427

- CHANGELOG.md
- settings/LocationCampuses.js
- settings/LocationLibraries.js
- settings/LocationLocations/LocationForm.js
Parens were always missing around institution codes on the
location-form, but no longer. Additionally, parens were always included,
even when codes were not present, after campuses and libraries, but no
longer.
> Improve parens handling around institution codes

- CHANGELOG.md
- settings/LocationLocations/LocationManager.js
Refresh lookup tables each time the component mounts. 
Queries in the manifest only run in the constructor, but this component may be unmounted/remounted without being destroyed/recreated, which means lookup tables will be stale if they change between unmount/remount. This scenario is described in the [comments](https://issues.folio.org/browse/UIORG-69?focusedCommentId=30161&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-30161) of UIORG-69.
> refresh lookup tables on mount

- settings/LocationCampuses.js
- settings/LocationLibraries.js
Queries in the manifest only run in the constructor, but this
component may be unmounted/remounted without being
destroyed/recreated, which means lookup tables will be stale
if they change between unmount/remount. This scenario is
described in the comments of UIORG-69.
> Refresh lookup tables each time component mounts

- CHANGELOG.md
- settings/LocationLocations/DetailsField.js
- settings/LocationLocations/LocationForm.js
`lib/structures` has been deprecated in favor of `lib/`.
Refs [STCOM-277](https://issues.folio.org/browse/STCOM-277)
> refactor away stripes-components/lib/structures

- package.json
- settings/LocationLocations/DetailsField.js
- settings/LocationLocations/LocationForm.js
- settings/ServicePoints/ServicePointForm.js
https://issues.folio.org/browse/STCOM-284
Components previously found in `@folio/stripes-components/lib/structures` are now at `@folio/stripes-components/lib`.
> STCOM-284 Update stripes-components paths

- CHANGELOG.md
- package.json
Add user-related permissions to the location-management permission set
so users can see last-updated-by details.
Refs [UIORG-76](https://issues.folio.org/browse/UIORG-76)
> add user permissions to permission set

- settings/LocationCampuses.js
- settings/LocationLibraries.js
- settings/LocationLocations/LocationForm.js
Some required fields were not correctly labeled. Some element IDs were
clearly cut-and-pasted from other elements and now reflect the elements
they pertain to.
> fix the typos

- CHANGELOG.md
- settings/LocationLocations/LocationManager.js
The way `asyncValidate` was written previously, validation errors would
appear immediately after a field was blurred but then would disappear as
soon as that secondary field was blurred. Since the errors didn't
persist across fields, validation was pretty much useless as it allowed
you to submit an invalid form.
> refactor asyncValidate to persist across blur

- CHANGELOG.md
- settings/LocationLocations/LocationForm.js
- settings/LocationLocations/LocationManager.js
When EntryManager was refactored into EntryWrapper and EntryManager to
get URL resources working, that had the side effect of overwriting the
resources property if resources were passed in via props. To be fair,
passing in resources withouth renaming the prop was really stupid. Now,
it's less stupid, so it works.
> prevent resource overwrite by EntryManager

- CHANGELOG.md
- package.json
- settings/LocationLocations/LocationForm.js
- settings/ServicePoints/ServicePointForm.js
Generation of HTML element-IDs in `<ConfirmationModal>` changed in
https://github.com/folio-org/stripes-components/commit/ce3ba8c996463a389ae3c3aeb36069d9a785ed69
and that broke a bunch of tests that relied on the old style of element
IDs. Happily, we can restore this behavior by passing in an ID prop that
matches the old format.
Refs [STCOM-317](https://issues.folio.org/browse/STCOM-317)
> pass id prop to ConfirmationModal

- test/ui-testing/locations.js
Tests for new institution, campus, and library were navigating away from
the element-creation screen before the create-entity request had
completed, causing a "There are unsaved changes; really leave?" dialog
to pop up. Tests now wait until the request has completed rather than
just for a specific timeout. This makes them more robust over slow
connections, or over connections to slow or remote servers. Previously,
tests were likely to pass locally but fail when run against a non-local
server.
> confirm creation before continuing

- test/ui-testing/locations.js
- On slower connections, sometimes requests wouldn't have
settled by the time the test started operating on the
assumption it had.
- Added conditional wait()s rather than timed-waits and
introduced extra ones.
> Tests Locations: Reworked `wait()` logic

- CHANGELOG.md
- settings/LocationLocations/LocationForm.js
- settings/LocationLocations/LocationManager.js
Check whether a location is in use by a holdings or item record before
attempting to remove it. This allows us to be more confident that a
DELETE request will be successful if we make it that far, and allows us
to show a nicer, more informative error message if we know such a
request would fail.
Refs [UIORG-86](https://issues.folio.org/browse/UIORG-86)
> validation use of locations before removal

- CHANGELOG.md
- settings/LocationLocations/LocationManager.js
It appears that under some circumstances redux-form will only submit
dirty form fields if a field was not provided to `props.initialValues`.
This is particularly relevant when creating new items because it means
that new item will not be correctly initialized if, say, the form has a
dropdown menu with a default selection.
https://github.com/erikras/redux-form/issues/701 may be relevant, at
least as far as understanding the behavior.
This behavior has never been observed locally but did appear reliably on
folio-testing. What a mystery.
Fixes [UIORG-109](https://issues.folio.org/browse/UIORG-109)
> provide default isActive value to new locations

- lib/RepeatableField/FieldRow.js
- lib/RepeatableField/RepeatableField.css
- lib/RepeatableField/RepeatableField.js
- lib/RepeatableField/index.js
- lib/RepeatableField/readme.md
- settings/LocationLocations/DetailsField.js
`stripes-components` is about to have breaking changes to `RepeatableField`, so to put off migrating this use of it, I copied over the `RepeatableField` code here temporarily. I didn't attempt to copy the git history this time, since I anticipate a very short shelf life for this code.
> Copy RepeatableField from stripes-components

- CHANGELOG.md
- package.json
- settings/ServicePoints/ServicePointDetail.js
Fixes
```
WARNING in ./node_modules/@folio/organization/settings/ServicePoints/ServicePointDetail.js 42:48-60
"export 'default' (imported as 'ViewMetaData') was not found in '@folio/stripes/smart-components'
```
for https://issues.folio.org/browse/FOLIO-1547
Includes `v2.5.1` release.
> Fix ViewMetaData import

- package.json
Noticed when running `yarn install` in `folio-org/platform-core` branch:
```
warning "@folio/organization > react-tether@1.0.2" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
```
With `<AutoSuggest>` now in `stripes-components`, `downshift` and `react-tether` are no longer dependencies of this repo.
> Remove downshift and react-tether

- CHANGELOG.md
- package.json
An array of service-points is now a required attribute of a location.
This change aligns the `service-points` API version with that for
`locations` which had been updated in #144.
Refs [UIORG-115](https://issues.folio.org/browse/UIORG-115), [MODINVSTOR-177](https://issues.folio.org/browse/MODINVSTOR-177)
> Align mod-inventory-storage dependency versions

- settings/LocationLocations/LocationForm.js
- settings/LocationLocations/LocationManager.js
redux-form doesn't like when we mutate the `initialValues` object inside the form. This caused infinite rendering loop when we set `enableReinitialize` to  `true`  previously. It was also causing issues with record duplication in UIORG-117. 
This PR moves it out of the location form and uses  `parseInitialValues` to do the massaging right before the form is initialized.
> Refactor detailsArray out of location form. Part of UIORG-117

- CHANGELOG.md
- settings/LocationCampuses.js
- settings/LocationInstitutions.js
- settings/LocationLibraries.js
`<ControlledVocab>` should have a `defaultProps` value for `sortby`, but
that value isn't being pushed down correctly so we're providing our own
prop here.
Refs [STSMACOM-139](https://issues.folio.org/browse/STSMACOM-139)
> provide sortby key to ControlledVocab

- CHANGELOG.md
- test/ui-testing/locations.js
This app used to check the ui-users version in its integration tests. I
don't know why it did that. I do know that wrecked tests that tried to
run with _only_ ui-organization installed.
Fixes [UIORG-121](https://issues.folio.org/browse/UIORG-121)
> don't check users version in tests

- test/ui-testing/locations.js
The title attribute is being phased out so tests must hang off other
elements. Likewise, remove the delete-confirmation tests because we
don't have reliable elements to hang them off. Really. You can click the
delete-confirmation button, but the toast messages don't have unique or
predictable IDs (because you can show more than one at a time) and we
don't want to rely on some translated field. So anyway, no more delete
confirmation tests.
Refs [STCOM-296](https://issues.folio.org/browse/STCOM-296)
> don't hang tests off title attribute

- test/ui-testing/locations.js
Sometimes, after removing an entry on a `<ControlledVocab>` page, the
browser appears to get stuck on that page and can't navigate away.
The timer fixes this problem, though adding it makes me very very very
very very very very very very very very very very very very very very
very very very very very very very very very very very very very very
very very very very very very very very very very very very very very
very very very very very very very very very very very very very very
very very very very very very very very very very very very very very
very very very very very very very very very very very very very very
very very very very very very very very very very very very very very
very very very very very very very very very very very very very very
very very very very very very …
> use timers to un-stall navigation after CV delete

- src/settings/LocationLocations/LocationForm.js
`<option>` labels need to be strings, not `<FormattedMessage>`s. Fixes
the regression introduced in #158.
> correctly display location status options

- src/settings/LocationCampuses.js
- src/settings/LocationLibraries.js
- src/settings/LocationLocations/LocationForm.js
An `<option>`'s `text` attribute must be a string, not an object, which
means we can't pass a `<FormattedMessage>` object.
> provide strings to `<option>` elements

- CHANGELOG.md
- src/settings/LocationCampuses.js
- src/settings/LocationInstitutions.js
- src/settings/LocationLibraries.js
- src/settings/LocationLocations/LocationManager.js
`<ControlledVocab>` needs to receive strings for some props in order to
avoid displaying `[object Object]` instead of, e.g. `Institution`,
`Campus`, etc in dialog boxes and toast alerts.
Fixes [UIORG-134](https://issues.folio.org/browse/UIORG-134)
> pass strings, not nodes, to ControlledVocab

- test/ui-testing/locations.js
Call `wait()`, not `evaluate()`, when confirming that rows have been
removed from a `<ControlledVocab>` list.
Restore delete-should-fail tests. These were disabled because there used
to be some bad interactions with the `setTimeout` code in `Callout` but
the `wait()` handling mentioned above seems to work around this.
Fixes [UIORG-136](https://issues.folio.org/browse/UIORG-136)
> better handling of delete confirmation

- test/ui-testing/locations.js
Logging during testing shows that if the script immediately starts
looping through the list of institutions after they load, it gets a list
that contains some institutions and some libraries. This makes no sense
whatsoever, and does not reflect what is displayed in the UI, and yet
that's what it reports on the console. If we wait, the UI and console
appear to be in sync.
I give up. I don't want to wait. I don't understand why we're out of
sync, or even _how_ we can be out of sync in this manner. Maybe if we
had the wrong list entirely, i.e. a list of all libraries, that would
make sense. But a list of half libraries and half institutions? I got
nothin' to explain that.
> wait longer before attempting delete

- package.json
- src/settings/ServicePoints/ServicePointDetail.js
- src/settings/ServicePoints/ServicePointForm.js
- test/bigtest/interactors/service-point-create.js
- test/bigtest/interactors/service-point-show.js
- test/bigtest/tests/service-point-create-test.js
- test/bigtest/tests/service-point-show-test.js
To add a hold shelf expiration period to the service points where pickup location/service point = yes. This will be used as the default expiration period for items on the hold shelf at the service point.
Part of this work has been done under: https://github.com/folio-org/ui-organization/pull/204 by @aditya-matukumalli. This PR adds ability to see hold shelf expiry period on the service point details screen. It also adds more tests.  
https://issues.folio.org/browse/UIORG-143
> Add hold shelf expiry period to service point. Fixes UIORG-143

- test/ui-testing/locations.js
Navigate away and back to the Organization > Locations page when
removing a location and confirming removal. Previously, Nightmare would
get hung up at this step and open a new-location layer (WTF?) and that
would cause all future tests to fail. It was a mess.
> better delete confirmation checks
